export {default as Navbar} from './Navbar';
export {default as Hero} from './Hero';
export {default as About} from './About';
export {default as Featuredpost} from './Featuredpost';
export {default as Gallery} from './Gallery';
export {default as Testimonial} from './Testimonial';
export {default as TestimonialCard} from './TestimonialCard';
export {default as Donate} from './Donate';
export {default as Footer} from './Footer'
